version: '3.8'

services:
  world-cars-next:
    container_name: world-cars-next
    restart: always
    build: .
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/world-cars-next
    working_dir: /usr/src/world-cars-next
    networks:
      - client-network

networks:
  client-network:
    driver: bridge
