version: '3.8'
services:
  world-cars-next:
    container_name: world-cars-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/world-cars-next
    working_dir: /usr/src/world-cars-next
    networks:
      - client-network
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
